/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"os"
	"sync"

	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)
	// to ensure that exec-entrypoint and run can make use of them.
	"golang.org/x/sync/errgroup"
	_ "k8s.io/client-go/plugin/pkg/client/auth"

	"github.com/google/uuid"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	k8sCache "sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/metrics/filters"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
	"sigs.k8s.io/controller-runtime/pkg/webhook"

	usernautdevv1alpha1 "github.com/redhat-data-and-ai/usernaut/api/v1alpha1"
	"github.com/redhat-data-and-ai/usernaut/internal/controller"
	"github.com/redhat-data-and-ai/usernaut/pkg/cache"
	"github.com/redhat-data-and-ai/usernaut/pkg/clients"
	"github.com/redhat-data-and-ai/usernaut/pkg/clients/ldap"
	"github.com/redhat-data-and-ai/usernaut/pkg/clients/snowflake"
	"github.com/redhat-data-and-ai/usernaut/pkg/common/structs"
	"github.com/redhat-data-and-ai/usernaut/pkg/config"
	"github.com/redhat-data-and-ai/usernaut/pkg/logger"
	"github.com/redhat-data-and-ai/usernaut/pkg/store"
	"github.com/sirupsen/logrus"

	// +kubebuilder:scaffold:imports
	"github.com/redhat-data-and-ai/usernaut/internal/httpapi/server"
)

var (
	scheme   = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

func init() {

	// initializing custom logger
	logger.Init()

	utilruntime.Must(clientgoscheme.AddToScheme(scheme))

	utilruntime.Must(usernautdevv1alpha1.AddToScheme(scheme))
	// +kubebuilder:scaffold:scheme
}

func main() {
	var metricsAddr string
	var enableLeaderElection bool
	var probeAddr string
	var secureMetrics bool
	var enableHTTP2 bool
	var tlsOpts []func(*tls.Config)
	flag.StringVar(&metricsAddr, "metrics-bind-address", "0", "The address the metrics endpoint binds to. "+
		"Use :8443 for HTTPS or :8080 for HTTP, or leave as 0 to disable the metrics service.")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "leader-elect", false,
		"Enable leader election for controller manager. "+
			"Enabling this will ensure there is only one active controller manager.")
	flag.BoolVar(&secureMetrics, "metrics-secure", true,
		"If set, the metrics endpoint is served securely via HTTPS. Use --metrics-secure=false to use HTTP instead.")
	flag.BoolVar(&enableHTTP2, "enable-http2", false,
		"If set, HTTP/2 will be enabled for the metrics and webhook servers")
	opts := zap.Options{
		Development: false,
	}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()

	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	// if the enable-http2 flag is false (the default), http/2 should be disabled
	// due to its vulnerabilities. More specifically, disabling http/2 will
	// prevent from being vulnerable to the HTTP/2 Stream Cancellation and
	// Rapid Reset CVEs. For more information see:
	// - https://github.com/advisories/GHSA-qppj-fm5r-hxr3
	// - https://github.com/advisories/GHSA-4374-p667-p6c8
	disableHTTP2 := func(c *tls.Config) {
		setupLog.Info("disabling http/2")
		c.NextProtos = []string{"http/1.1"}
	}

	if !enableHTTP2 {
		tlsOpts = append(tlsOpts, disableHTTP2)
	}

	webhookServer := webhook.NewServer(webhook.Options{
		TLSOpts: tlsOpts,
	})

	// Metrics endpoint is enabled in 'config/default/kustomization.yaml'. The Metrics options configure the server.
	// More info:
	// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/server
	// - https://book.kubebuilder.io/reference/metrics.html
	metricsServerOptions := metricsserver.Options{
		BindAddress:   metricsAddr,
		SecureServing: secureMetrics,
		// TODO(user): TLSOpts is used to allow configuring the TLS config used for the server. If certificates are
		// not provided, self-signed certificates will be generated by default. This option is not recommended for
		// production environments as self-signed certificates do not offer the same level of trust and security
		// as certificates issued by a trusted Certificate Authority (CA). The primary risk is potentially allowing
		// unauthorized access to sensitive metrics data. Consider replacing with CertDir, CertName, and KeyName
		// to provide certificates, ensuring the server communicates using trusted and secure certificates.
		TLSOpts: tlsOpts,
	}

	if secureMetrics {
		// FilterProvider is used to protect the metrics endpoint with authn/authz.
		// These configurations ensure that only authorized users and service accounts
		// can access the metrics endpoint. The RBAC are configured in 'config/rbac/kustomization.yaml'. More info:
		// https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/filters#WithAuthenticationAndAuthorization
		metricsServerOptions.FilterProvider = filters.WithAuthenticationAndAuthorization
	}

	watchedNs := os.Getenv("WATCHED_NAMESPACE")
	if watchedNs == "" {
		watchedNs = "usernaut"
	}

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		Metrics:                metricsServerOptions,
		WebhookServer:          webhookServer,
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         enableLeaderElection,
		LeaderElectionID:       "dd1e5158.operator.dataverse.redhat.com",
		Cache: k8sCache.Options{
			DefaultNamespaces: map[string]k8sCache.Config{
				watchedNs: {},
			},
		},
		// LeaderElectionReleaseOnCancel defines if the leader should step down voluntarily
		// when the Manager ends. This requires the binary to immediately end when the
		// Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
		// speeds up voluntary leader transitions as the new leader don't have to wait
		// LeaseDuration time first.
		//
		// In the default scaffold provided, the program ends immediately after
		// the manager stops, so would be fine to enable this option. However,
		// if you are doing or is intended to do any operation such as perform cleanups
		// after the manager stops then its usage might be unsafe.
		// LeaderElectionReleaseOnCancel: true,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	appConf, err := config.GetConfig()
	if err != nil {
		setupLog.Error(err, "unable to create config")
		os.Exit(1)
	}

	ldapConn, err := ldap.InitLdap(appConf.LDAP)
	if err != nil {
		setupLog.Error(err, "failed to initialize LDAP connection")
		os.Exit(1)
	}

	cache, err := cache.New(&appConf.Cache)
	if err != nil {
		setupLog.Error(err, "failed to initialize cache")
		os.Exit(1)
	}

	// Create shared cache mutex to prevent race conditions between GroupReconciler and UserOffboardingJob
	sharedCacheMutex := &sync.RWMutex{}

	// Create store layer that wraps cache with prefixed keys and encapsulated operations
	dataStore := store.New(cache)

	if err = preloadCache(*appConf, dataStore, sharedCacheMutex); err != nil {
		setupLog.Error(err, "failed to preload cache")
		os.Exit(1)
	}

	if err = (&controller.GroupReconciler{
		Client:     mgr.GetClient(),
		Scheme:     mgr.GetScheme(),
		AppConfig:  appConf,
		Store:      dataStore,
		LdapConn:   ldapConn,
		CacheMutex: sharedCacheMutex,
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Group")
		os.Exit(1)
	}

	// Initialize backend clients for the periodic tasks
	backendClients := make(map[string]clients.Client)
	for _, backend := range appConf.Backends {
		if backend.Enabled {
			client, err := clients.New(backend.Name, backend.Type, appConf.BackendMap)
			if err != nil {
				setupLog.Error(err, "failed to initialize backend client for periodic tasks",
					"backend", backend.Name, "type", backend.Type)
				os.Exit(1)
			}
			backendClients[fmt.Sprintf("%s_%s", backend.Name, backend.Type)] = client
		}
	}

	ptr, err := controller.NewPeriodicTasksReconciler(
		mgr.GetClient(), sharedCacheMutex, cache, dataStore, ldapConn, backendClients)
	if err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "PeriodicTasks")
		os.Exit(1)
	}
	if err = ptr.AddToManager(mgr); err != nil {
		setupLog.Error(err, "unable to add controller to manager", "controller", "PeriodicTasks")
		os.Exit(1)
	}
	// +kubebuilder:scaffold:builder

	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up health check")
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up ready check")
		os.Exit(1)
	}

	apiServer := server.NewAPIServer(appConf, dataStore)
	go func() {
		if err := apiServer.Start(); err != nil {
			setupLog.Error(err, "failed to start HTTP API server")
			os.Exit(1)
		}
	}()
	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}

// storeUsersInCache stores users in the cache and returns an error if any user fails to be stored
func storeUsersInCache(ctx context.Context, users map[string]*structs.User, dataStore *store.Store,
	cacheMutex *sync.RWMutex, backendKey string, log *logrus.Entry) error {
	for _, user := range users {
		cacheMutex.Lock()
		err := dataStore.User.SetBackend(ctx, user.GetEmail(), backendKey, user.ID)
		cacheMutex.Unlock()
		if err != nil {
			log.WithError(err).Error("failed to store user in cache")
			return err
		}
	}
	return nil
}

// snowflakeAsyncState holds state needed for Snowflake async continuation after preload
type snowflakeAsyncState struct {
	client     *snowflake.SnowflakeClient
	lastUser   string
	backendKey string
}

// Preload the cache with all the users and teams from the backends
// This is done to avoid hitting the backend for every request
// and to improve the performance of the application
// This is done only once at the start of the application
// and the cache is flushed when the application is restarted
// Optimized to use goroutines for parallel processing of backends
func preloadCache(appConfig config.AppConfig, dataStore *store.Store, cacheMutex *sync.RWMutex) error {
	ctx := context.Background()

	// Add request ID for tracking this cache preload operation in logs
	ctx = logger.WithRequestId(ctx, types.UID(uuid.New().String()))

	// Use errgroup for concurrent processing with proper error handling
	g, ctx := errgroup.WithContext(ctx)

	// States for Snowflake async continuation (protected by mutex for goroutine safety)
	// Using a slice to support multiple Snowflake backends (dev, pre-prod, prod, etc.)
	var snowflakeStates []*snowflakeAsyncState
	var snowflakeStateMutex sync.Mutex

	// Process each backend concurrently
	for _, backendObj := range appConfig.Backends {

		// Capture loop variable for goroutine
		backend := backendObj

		// don't preload the cache in case of a disabled backend
		if !backend.Enabled {
			log := logger.Logger(ctx).
				WithFields(logrus.Fields{
					"backend":   backend.Name,
					"type":      backend.Type,
					"component": "preloadCache",
				})
			log.Warn("Backend is disabled, skipping preload")
			continue
		}

		// Launch goroutine for each backend
		g.Go(func() error {
			log := logger.Logger(ctx).
				WithFields(logrus.Fields{
					"backend":   backend.Name,
					"type":      backend.Type,
					"component": "preloadCache",
				})

			log.Info("preloading cache with users and teams from backend")

			backendClient, err := clients.New(backend.Name, backend.Type, appConfig.BackendMap)
			if err != nil {
				log.WithError(err).Error("failed to create backend client")
				return err
			}

			backendKey := backend.Name + "_" + backend.Type

			// Handle Snowflake specially to capture last user for async continuation
			if backend.Type == "snowflake" {
				sfClient := backendClient.(*snowflake.SnowflakeClient)
				users, _, lastUser, err := sfClient.FetchAllUsersWithCursor(ctx)
				if err != nil {
					log.WithError(err).Error("failed to fetch users from Snowflake")
					return err
				}

				if err := storeUsersInCache(ctx, users, dataStore, cacheMutex, backendKey, log); err != nil {
					return err
				}

				// Save state for async continuation (append to slice for multiple Snowflake backends)
				snowflakeStateMutex.Lock()
				snowflakeStates = append(snowflakeStates, &snowflakeAsyncState{
					client:     sfClient,
					lastUser:   lastUser,
					backendKey: backendKey,
				})
				snowflakeStateMutex.Unlock()

				log.WithFields(logrus.Fields{
					"users":     len(users),
					"last_user": lastUser,
				}).Info("Snowflake preload complete, will continue async")
			} else {
				// Other backends: existing flow
				users, _, err := backendClient.FetchAllUsers(ctx)
				if err != nil {
					log.WithError(err).Error("failed to fetch users from backend")
					return err
				}

				if err := storeUsersInCache(ctx, users, dataStore, cacheMutex, backendKey, log); err != nil {
					return err
				}

				log.WithField("users", len(users)).Info("preloaded users from backend")
			}

			// Fetch all the teams and store them in the TeamStore cache
			// Teams are stored by their transformed name (as returned by the backend)
			// During reconciliation, if a team is not found in GroupStore, it will
			// fallback to TeamStore and migrate the data to GroupStore
			teams, err := backendClient.FetchAllTeams(ctx)
			if err != nil {
				log.WithError(err).Error("failed to fetch teams from backend")
				return err
			}

			for _, team := range teams {
				cacheMutex.Lock()
				err := dataStore.Team.SetBackend(ctx, team.GetName(), backendKey, team.ID)
				cacheMutex.Unlock()
				if err != nil {
					log.WithError(err).Error("failed to store team in cache")
					return err
				}
			}

			log.WithField("teams", len(teams)).Info("successfully preloaded teams from backend")

			return nil
		})
	}

	// Wait for all goroutines to complete and return any errors
	if err := g.Wait(); err != nil {
		return err
	}

	setupLog.Info("cache preload completed for all backends")

	// Start async continuation for all Snowflake backends (after all preloads done)
	for _, state := range snowflakeStates {
		if state.lastUser != "" {
			startSnowflakeAsyncContinuation(ctx, state, dataStore, cacheMutex)
		}
	}

	return nil
}

// startSnowflakeAsyncContinuation starts a background goroutine to fetch remaining Snowflake users
// and write them to cache. This function returns immediately after starting the goroutine.
func startSnowflakeAsyncContinuation(
	originalCtx context.Context,
	state *snowflakeAsyncState,
	dataStore *store.Store,
	cacheMutex *sync.RWMutex,
) {
	// Create a fresh context since the errgroup context is canceled after g.Wait() returns
	// Transfer the logger (with request ID) from original context for traceability
	asyncCtx := context.Background()
	if entry := logger.Logger(originalCtx); entry != nil {
		asyncCtx = context.WithValue(asyncCtx, logger.RequestIdKey, entry)
	}
	userChan, errChan := state.client.FetchRemainingUsersAsync(asyncCtx, state.lastUser)

	// Consumer goroutine - writes to cache
	go func() {
		log := logger.Logger(asyncCtx).WithFields(logrus.Fields{
			"component": "snowflake-async",
			"backend":   state.backendKey,
		})
		count := 0
		failedCount := 0

		for user := range userChan {
			cacheMutex.Lock()
			err := dataStore.User.SetBackend(asyncCtx, user.GetEmail(), state.backendKey, user.ID)
			cacheMutex.Unlock()

			if err != nil {
				failedCount++
				log.WithError(err).WithField("email", user.GetEmail()).Warn("failed to store user in cache")
				continue
			}
			count++

			if count%1000 == 0 {
				log.WithField("users_loaded", count).Info("Snowflake async progress")
			}
		}

		if err := <-errChan; err != nil {
			log.WithError(err).Error("Snowflake async fetch failed")
		} else {
			log.WithFields(logrus.Fields{
				"users_cached":       count,
				"users_failed_cache": failedCount,
			}).Info("Snowflake async fetch complete")
		}
	}()

	setupLog.Info("Snowflake async continuation started")
}
